### ISSUE TITLE
Shop Name is not displayed 

### ISSUE THREAD

**Issue by pinalj** [TycheSoftwares/woocommerce-delivery-notes#73] opened 2018-11-27 10:55 UTC
The Shop name has been added in the plugin settings. However, it's not being displayed in the invoice, delivery note or receipt printed from the dashboard or the customer email.

This has been tested with WP 5.0 beta release.

**Comment by priyanka-tychesoftwares** [comment] 2018-12-13 06:51
This is not a bug from our plugin. This is how the functionality works. If the Shop logo is set then the Shop name will not display in the invoice. And if the Shop logo is not set then shop name will display in the invoice. Hence I am closing this issue.

**Closed by priyanka-tychesoftwares** 2018-12-13 06:51 UTC
Labels: WP 5.0, bug
