### ISSUE TITLE
Icon is missing on Order page Action tab

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-notes#39] opened 2018-02-15 11:17 UTC
Print Invoice, Print Delivery note, Print receipt icon are missing on order page

See the screenshot: https://www.screencast.com/t/B024F4FU

tested with WooCommerce 3.3.1

**Comment by hjoelr** [comment] 2018-02-19 20:26
This is a duplicate of #37.

**Comment by hjoelr** [comment] 2018-02-21 22:06
@apeksha10 @bhavik-kiri I have a PR fix for this issue at #40.

**Comment by hjoelr** [comment] 2018-02-22 13:22
This has been fixed in version 4.4.2 which includes commit dd834210d6c1d64be433dd0781e0a15ba3142e1c.

**Comment by moxajogani** [comment] 2019-03-27 10:43
As the fix for this issue is released in version 4.4.2, closing this issue.

**Closed by moxajogani** 2019-03-27 10:43 UTC
Labels: bug
